addons:
  apt:
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - xvfb
    sources:
      - ubuntu-toolchain-r-test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

env:
  - TARGET_ARCH=x64

install:
  - export CXX="g++-4.8"
  - yarn
  - cd app && yarn && cd ..
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

language: node_js
node_js:
  - 8
  - 7

os:
  - linux

script:
  - node --version
  - yarn lint
  - yarn package
  - yarn test
  - yarn test-e2e

sudo: false
